{{- if .Values.postgres.enabled }}
# PostgreSQL superuser credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.cluster.superuserSecret }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.cluster.superuserSecretData.username | quote }}
  password: {{ .Values.postgres.cluster.superuserSecretData.password | quote }}
{{- end }}
