{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-primary-lb
  labels:
    cnpg.io/cluster: {{ .Release.Name }}
    {{ include "mclabels.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    cnpg.io/cluster: {{ .Release.Name }}
    role: primary
{{- end }}
