apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    mapcolonies.io/grafana-datasources: "true"
data:
{{ (.Files.Glob "files/default-datasources.yaml").AsConfig | indent 2 }}
