apiVersion: v1
kind: Secret
metadata:
  name: grafana-webhooks
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
{{- with .Values.grafana.alertingTeamsWebhooks }}
stringData:
  {{- range . }}
  {{- if .url }}
  {{ upper .team }}_WEBHOOK: {{ .url | quote }}
  {{- end }}
  {{- end }}
{{- end }}
