apiVersion: 1
groups:
  - orgId: 1
    name: alloy_clustering
    folder: Alloy
    interval: 1m
    rules:
      - uid: mx-cl-conv
        title: ClusterNotConverging
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: stddev by (cluster, namespace, job, cluster_name) (sum without (state) (cluster_node_peers)) != 0
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [0]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: classic_conditions
        noDataState: OK
        execErrState: Error
        for: 10m
        labels:
          severity: warning
          alert_team: infra
        annotations:
          summary: Cluster is not converging.
          description: "Cluster is not converging: nodes report different number of peers in the cluster. Job is {{ $labels.job }}"

      - uid: mx-nd-cnt
        title: ClusterNodeCountMismatch
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: "sum without (state) (cluster_node_peers) != on (cluster, namespace, job, cluster_name) group_left count by (cluster, namespace, job, cluster_name) (cluster_node_info)"
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [0]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: classic_conditions
        noDataState: OK
        execErrState: Error
        for: 15m
        labels:
          severity: warning
          alert_team: infra
        annotations:
          summary: Nodes report different number of peers vs. the count of observed Alloy metrics.
          description: "Nodes report different number of peers vs. the count of observed Alloy metrics. Some Alloy metrics may be missing or the cluster is in a split brain state. Job is {{ $labels.job }}"

      - uid: mx-nd-heal
        title: ClusterNodeUnhealthy
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: cluster_node_gossip_health_score > 0
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [0]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: classic_conditions
        noDataState: OK
        execErrState: Error
        for: 10m
        labels:
          severity: warning
          alert_team: infra
        annotations:
          summary: Cluster unhealthy.
          description: "Cluster node is reporting a gossip protocol health score > 0. Job is {{ $labels.job }}"

      - uid: mx-nd-cnfl
        title: ClusterNodeNameConflict
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: 'sum by (cluster, namespace, job, cluster_name) (rate(cluster_node_gossip_received_events_total{event="node_conflict"}[2m])) > 0'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [0]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: classic_conditions
        noDataState: OK
        execErrState: Error
        for: 10m
        labels:
          severity: warning
          alert_team: infra
        annotations:
          summary: Cluster Node Name Conflict.
          description: "A node tried to join the cluster with a name conflicting with an existing peer. Job is {{ $labels.job }}"

      - uid: mx-nd-term
        title: ClusterNodeStuckTerminating
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: 'sum by (cluster, namespace, job, instance, cluster_name) (cluster_node_peers{state="terminating"}) > 0'
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [0]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: classic_conditions
        noDataState: OK
        execErrState: Error
        for: 10m
        labels:
          severity: warning
          alert_team: infra
        annotations:
          summary: Cluster node stuck in Terminating state.
          description: "There is a node within the cluster that is stuck in Terminating state. Job is {{ $labels.job }}"

      - uid: mx-cl-drft
        title: ClusterConfigurationDrift
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: "count without (sha256) (max by (cluster, namespace, sha256, job, cluster_name) (alloy_config_hash{cluster_name!=\"\"} and on(cluster, namespace, job, cluster_name) cluster_node_info)) > 1"
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [0]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: classic_conditions
        noDataState: OK
        execErrState: Error
        for: 5m
        labels:
          severity: warning
          alert_team: infra
        annotations:
          summary: Cluster configuration drifting.
          description: "Cluster nodes are not using the same configuration file. Job is {{ $labels.job }}"
