global:
  enable-services:
    enabled: true
    catalog-app: true
    catalog-web-app-bff: true
    mc-web-tools: true
    k8s-services-list: true
    mc-thumbnail-generator: false

catalog-app:
  configValues:
    image:
      repository: app/catalog-app
      tag: v6.5.0

catalog-web-app-bff:
  configValues:
    image:
      repository: app/catalog-web-app-bff
      tag: v4.3.2

mc-web-tools:
  configValues:
    image:
      repository: app/mc-web-tools
      tag: v3.1.3

k8s-services-list:
  configValues:
    image:
      repository: common/k8s-services-list
      tag: v1.3.3

mc-thumbnail-generator:
  configValues:
    image:
      repository: common/mc-thumbnail-generator
      tag: v3.1.2
