# ====================================================================================================
# Global
# ====================================================================================================
global:
  owner: app
  currentSubChart: catalog
  enable-services:
    enabled: true
    catalog-app: true
    catalog-web-app-bff: true
    mc-web-tools: true
    k8s-services-list: true
    mc-thumbnail-generator: false
# ====================================================================================================
# Shared
# ====================================================================================================
  shared:
    servedEntityTypes: RECORD_ALL
    accessToken:
      attributeName: token
      injectionType: queryParam
      tokenValue: TOKEN
    rasterIngestionFilesStructure: '{"data": {"allowedExt": [".gpkg"], "selectableExt": [".gpkg"], "relativeToAOIDirPath": "./data", "producerFileName": "*", "selectablePattern": "*"}, "product": {"allowedExt": [".shp", ".shx", ".dbf", ".prj", ".sbn", ".sbx", ".xml", ".cpg", ".qix"], "selectableExt": [".shp"], "relativeToAOIDirPath": "./shape", "producerFileName": "Product", "selectablePattern": "Product"}, "shapeMetadata": {"allowedExt": [".shp", ".shx", ".dbf", ".prj", ".sbn", ".sbx", ".xml", ".cpg", ".qix"], "selectableExt": [".shp"], "relativeToAOIDirPath": "./shape", "producerFileName": "ShapeMetadata", "selectablePattern": "ShapeMetadata"}}'
    sso:
      enabled: false
      redirectUrl:
        ui:
        tools:

# ====================================================================================================
# Catalog App
# ====================================================================================================
catalog-app:
  configValues:
    image:
      repository: app/catalog-app
      tag: v4.5.0

# ====================================================================================================
# Catalog Web App BFF
# ====================================================================================================
catalog-web-app-bff:
  configValues:
    image:
      repository: app/catalog-web-app-bff
      tag: v4.0.6

# ====================================================================================================
# MC Web Tools
# ====================================================================================================
mc-web-tools:
  configValues:
    image:
      repository: app/mc-web-tools
      tag: v3.1.3

# ====================================================================================================
# K8S Services List
# ====================================================================================================
k8s-services-list:
  configValues:
    image:
      repository: common/k8s-services-list
      tag: v1.3.3

# ====================================================================================================
# MC Thumbnail Generator
# ====================================================================================================
mc-thumbnail-generator:
  configValues:
    image:
      repository: common/mc-thumbnail-generator
      tag: v3.1.2
