apiVersion: v2
name: gatekeeper-constraints
description: Deploy Gatekeeper ConstraintTemplates and Constraints
type: application
version: 1.0.0
annotations:
  domain: infra
dependencies:
  - name: gatekeeper
    version: 3.22.0
    repository: https://open-policy-agent.github.io/gatekeeper/charts
