enabled: false
host: ""
service: ""
port: ""
tls:
  enabled: false
  termination: "edge"
  insecureEdgeTerminationPolicy: "Redirect"
  caCertificate: ""
  certificate: ""
  key: ""
  destinationCACertificate: ""
