sftpgo:
  image:
    tag: v2.7-openshift

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10000"
  
  podLabels:
    mapcolonies.io/owner: infra
    mapcolonies.io/component: infrastructure
    mapcolonies.io/part-of: storage

  envVars:
    - name: SFTPGO_DEFAULT_ADMIN_USERNAME
      valueFrom:
        secretKeyRef:
          name: sftp-admin-credentials
          key: username
    - name: SFTPGO_DEFAULT_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sftp-admin-credentials
          key: password
    - name: SFTPGO_HTTPD_PROXY_HEADERS
      value: 'true'
    - name: SFTPGO_HTTPD_COOKIE_SECURE
      value: 'true'
    - name: SFTPGO_HTTPD_COOKIE_SAMESITE
      value: lax
    - name: SFTPGO_HTTPD_ENABLED
      value: 'true'
    - name: SFTPGO_LOG_LEVEL
      value: info

  service:
    type: ClusterIP    

  services: 
    lb:
      type: LoadBalancer
      ports: # Define extra ports if needed for LoadBalancer service
        sftp: 
          port: 2022
        webdav:
          port: 5005

  webdavd:
    enabled: true
    
sftpgo-node-exporter:
  envVars:
    - name: PARENT_DIR
      value: /mnt

  extraArgs:
    - --collector.textfile.directory=/var/lib/node_exporter/textfile_collector
