apiVersion: v2
name: alertmanager
description: A Helm chart for Alertmanager
annotations:
  domain: infra
type: application
version: 1.0.0
appVersion: v0.27.0
dependencies:
  - name: alertmanager
    version: 1.13.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: openshift-routes
    version: 1.0.2
    repository: oci://acrarolibotnonprod.azurecr.io/helm/common
