apiVersion: v2
name: sftpgo-node-exporter
description: Node exporter for SFTPGo deployment
version: 1.0.0
appVersion: v1.8.2.4
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
