mclabels:
  owner: infra
  component: infrastructure
  partOf: storage
  prometheus:
    enabled: true
    port: 9100
  logScraping: true

replicaCount: 1

port: 9100
targetPort: 9100

volumeMounts: []
  # - name: pvc-name
  #   mountPath: /mnt

volumes: []
  # - name: pvc-name
  #   persistentVolumeClaim:
  #     claimName: pvc-name

image:
  repository: quay.io/prometheus/node-exporter
  imagePullPolicy: IfNotPresent

imagePullSecrets: []

resources:
  requests:
    memory: "128Mi"
    cpu: "200m"
  limits:
    memory: "256Mi"
    cpu: "500m"

## Additional container arguments
##
extraArgs: []

# -- Annotations to be added to pods.
podAnnotations: {}

envVars: []
  # - name: SOME_ENV_VAR
  #   value: SOME_VALUE
  # - name: SOME_ENV_VAR2
  #   valueFrom:
  #     secretKeyRef:
  #       name: SOME_SECRET_NAME
  #       key: SOME_SECRET_KEY
  # - name: SOME_ENV_VAR3
  #   valueFrom:
  #     configMapKeyRef:
  #       name: SOME_CONFIGMAP_NAME
  #       key: SOME_CONFIGMAP_KEY
