# ====================================================================================================
# Raster-Catalog-Manager
# ====================================================================================================
raster-catalog-manager:
  image:
    repository: raster/raster-catalog-manager
    tag: "v7.4.0"
  configManagement:
    offlineMode: true

# ====================================================================================================
# Job-Tracker
# ====================================================================================================
job-tracker:
  image:
    repository: raster/job-tracker
    tag: "v5.3.1"
  configManagement:
    offlineMode: true

  taskFlowManager:
    ingestionTasksFlow:
      - validation
      - create-tasks
      - tilesMerging
      - tiles-deletion
      - finalize
    exportTasksFlow:
      - init
      - tilesExporting
      # - polygon-parts # disabled by design until we will support it
      - finalize
    seedTasksFlow:
      - TilesSeeding
    deleteLayerTasksFlow:
      - delete
      - tiles-deletion

# ====================================================================================================
# Polygon-Parts-Manager
# ====================================================================================================
polygon-parts-manager:
  image:
    repository: raster/polygon-parts-manager
    tag: v3.5.1
  imagePullPolicy: IfNotPresent # TODO: set the default value in the service as `IfNotPresent`
  configManagement:
    offlineMode: true
  env:
    application:
      entities:
        polygonParts:
          minAreaSquareDeg: 1e-12 # TODO: remove after set this as the default value within service
      validation:
        areaThresholdSquareMeters: 10 # TODO: remove after set this as the default value within service

# ====================================================================================================
# Cleaner
# ====================================================================================================
cleaner:
  image:
    repository: raster/cleaner
    tag: "v1.2.1"
  configManagement:
    offlineMode: true
    version: "latest" # TODO: remove after set this as the default value within service
  env:
    targetPort: 8080 # TODO - remove after set this as the default value within service
    jobnik:
      worker: # TODO - remove after set this as the default value within service
        concurrency: 1
    worker:
      capabilities:
        pairs: # TODO - remove after set this as the default value within service
          - job: "Ingestion_Update"
            task: "tiles-deletion"
          - job: "Delete_Layer"
            task: "tiles-deletion"

# ====================================================================================================
# Files-Server
# ====================================================================================================
files-server:
  nginx:
    image:
      repository: common/nginx
      tag: v2.3.1
    imagePullPolicy: IfNotPresent # TODO: set the default value in the service (nginx repo) as `IfNotPresent`
    nameOverride: files-server
    route:
      rewriteTarget: "/"

    prometheusExporter:
      image:
        repository: common/nginx/nginx-prometheus-exporter
        tag: 1.4.1
 
# ====================================================================================================
# Nginx-S3-Gateway
# ====================================================================================================
nginx-s3-gateway:
  image:
    repository: common/nginx-s3-gateway
    tag: v3.0.2
