# ====================================================================================================
# Raster-Catalog-Manager
# ====================================================================================================
raster-catalog-manager:
  enabled: true
  image:
    repository: raster/raster-catalog-manager
    tag: "v7.1.0"

  db:
    schema: "RasterCatalogManager"

# ====================================================================================================
# Job-Tracker
# ====================================================================================================
job-tracker:
  enabled: true
  image:
    repository: raster/job-tracker
    tag: "v5.0.0"

  taskFlowManager:
    ingestionTasksFlow:
      - validation
      - create-tasks
      - tilesMerging
      - finalize
    exportTasksFlow:
      - init
      - tilesExporting
      - finalize
    seedTasksFlow:
      - TilesSeeding

# ====================================================================================================
# Polygon-Parts-Worker
# ====================================================================================================
polygon-parts-worker:
  enabled: true
  image:
    repository: raster/polygon-parts-worker
    tag: v2.1.7

  jobDefinitions:
    tasks:
      validation:
        chunkMaxVertices: 2500
        maxAttempts: 3
        smallGeometriesPercentageThreshold: 5
        smallHolesPercentageThreshold: 5
        reportsDownloadPath: "/downloads/validation-reports"

# ====================================================================================================
# Polygon-Parts-Manager
# ====================================================================================================
polygon-parts-manager:
  enabled: true
  image:
    repository: raster/polygon-parts-manager
    tag: v3.1.0

  db:
    schema: "polygon_parts"

# ====================================================================================================
# Files-Server
# ====================================================================================================
files-server:
  enabled: true
  nginx:
    enabled: true
    image:
      repository: common/nginx
      tag: "v2.1.1"

# ====================================================================================================
# Nginx-S3-Gateway
# ====================================================================================================
nginx-s3-gateway:
  enabled: true
  image:
    repository: common/nginx-s3-gateway
    tag: v3.0.2
