keycloak:
  global:
    security:
      allowInsecureImages: true

  commonLabels:
    mapcolonies.io/component: "infrastructure"
    mapcolonies.io/part-of: "monitoring" # Is it?
    mapcolonies.io/owner: "infra"
    mapcolonies.io/alloy-api-logs: "false"
    mapcolonies.io/criticality: "internal"

  serviceAccount:
    create: false

  metrics:
    enabled: true

  postgresql:
    enabled: false

  proxy: "edge"
  
  production: true
