apiVersion: v2
name: core-stack
description: A Helm chart for deploying MinIO, Redis, and PostgreSQL
annotations:
  domain: infra
version: 1.0.0
dependencies:
  - name: minio
    version: 14.7.0
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: redis
    version: 18.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 13.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: elasticsearch
    version: 21.3.0
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
