apiVersion: v2
name: serving
description: A Helm chart for Raster serving services
annotations:
  domain: raster
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: pycsw
    version: 6.4.1
    condition: pycsw.enabled
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster

  - name: pycsw
    version: 6.4.1
    condition: pycsw-private.enabled
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster
    alias: pycsw-private

  - name: mapproxy
    version: 1.9.2
    condition: mapproxy.enabled
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster

  - name: pp-geoserver
    version: 3.0.0
    condition: pp-geoserver.enabled
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster

  - name: redis
    version: 18.5.0
    condition: redis.enabled
    repository: https://charts.bitnami.com/bitnami
