# ====================================================================================================
# Pycsw
# ====================================================================================================
pycsw:
  enabled: true
  replicaCount: 1
  image:
    repository: common/pycsw
    tag: "v6.4.1"
    pullPolicy: Always

  mclabels:
    component: backend
    partOf: serving
    owner: raster
    gisDomain: raster
    prometheus:
      enabled: true
      port: 8080
    logScraping: true

  filterProductStatus: true

  env:
    # FLAG
    loglevel: WARNING
    db:
      schema: RasterCatalogManager
      requirePassword: true
    maxrecords: null
    logfile: ""
    uwsgi:
      # FLAG
      processes: 6
      # FLAG
      threads: 2
      statsServer:
        enabled: true
        stats: 1717
        statsMinify: true
    cors:
      enabled: true
      allowedOrigin: "*"
      allowedHeaders: "x-api-key"

  resources:
    enabled: false
    value:
      # FLAG
      limits:
        cpu: 1
        memory: 1.5Gi
      requests:
        cpu: 0.25
        memory: 1.5Gi

  nginx:
    image:
      repository: nginx-otel-unprivileged
      tag: "v1.0.0"
    replicaCount: 1
    enabled: true

    nginxTargetPort: 8080
    targetPort: 8080

    authorization:
      enabled: true
      domain: "raster"
      token:
        queryName: token

    resources:
      enabled: false
      value:
        # FLAG
        limits:
          cpu: 0.25
          memory: 350Mi
        requests:
          cpu: 0.0625
          memory: 350Mi

    route:
      enabled: true
      path: /api/raster/v1
      timeout:
        enabled: false # defaults to 30s by openshift
        duration: 60s # supported units (us, ms, s, m, h, d)
      tls:
        enabled: true
        useCerts: true

    ingress:
      enabled: false
      path: /api/raster/v1
      tls:
        enabled: true
        useExternal: ""

  uwsgiExporter:
    imagePullPolicy: Always
    image:
      repository: "timonwong/uwsgi-exporter"
      tag: "latest"
    env:
      logLevel: info # one of [debug, info, warn, error]
    port: 9117
    resources:
      enabled: false
      value:
        limits:
          cpu: 0.1
          memory: 128Mi
        requests:
          cpu: 0.025
          memory: 128Mi

# ====================================================================================================
# Pycsw-Private
# ====================================================================================================
pycsw-private:
  enabled: true
  replicaCount: 1
  image:
    repository: common/pycsw
    tag: "v6.4.1"
    pullPolicy: Always

  mclabels:
    component: backend
    partOf: serving
    owner: raster
    gisDomain: raster
    prometheus:
      enabled: true
      port: 9117
    logScraping: true

  env:
    # FLAG
    loglevel: WARNING
    db:
      schema: RasterCatalogManager
      requirePassword: true
    maxrecords: null
    logfile: ""
    uwsgi:
      # FLAG
      processes: 6
      # FLAG
      threads: 2
      statsServer:
        enabled: true
        stats: 1717
        statsMinify: true

  resources:
    enabled: false
    value:
      # FLAG
      limits:
        cpu: 1
        memory: 1.5Gi
      requests:
        cpu: 0.25
        memory: 1.5Gi

  nginx:
    image:
      repository: nginx-otel-unprivileged
      tag: "v1.0.0"
    replicaCount: 1
    enabled: true

    nginxTargetPort: 8080
    targetPort: 8080

    authorization:
      enabled: true
      domain: "raster"
      token:
        queryName: token

    resources:
      enabled: false
      value:
        # FLAG
        limits:
          cpu: 0.25
          memory: 350Mi
        requests:
          cpu: 0.0625
          memory: 350Mi

    route:
      enabled: false
      path: /api/raster/v1
      timeout:
        enabled: false # defaults to 30s by openshift
        duration: 60s # supported units (us, ms, s, m, h, d)
      tls:
        enabled: true
        useCerts: true

    ingress:
      enabled: false
      path: /api/raster/v1
      tls:
        enabled: true
        useExternal: ""

  uwsgiExporter:
    image:
      repository: "timonwong/uwsgi-exporter"
      tag: "latest"
      imagePullPolicy: Always
    env:
      logLevel: info # one of [debug, info, warn, error]
    port: 9117
    resources:
      enabled: false
      value:
        limits:
          cpu: 0.1
          memory: 128Mi
        requests:
          cpu: 0.025
          memory: 128Mi

# ====================================================================================================
# MapProxy
# ====================================================================================================
mapproxy:
  enabled: true

  mclabels:
    component: backend
    partOf: serving
    owner: raster
    gisDomain: raster
    prometheus:
      enabled: true
      port: 8080
    logScraping: true

  db:
    schema: MapproxyConfig
  podAnnotations: {}

  tracing:
    enabled: true
    # FLAG
    samplingRatioDenominator: 100
  metrics:
    enabled: true
    prometheus:
      scrape: true
      port: 9117

  initContainer:
    image:
      repository: mapproxinator
      tag: "v1.2.5"
      pullPolicy: Always
    env:
      logLevel: info
    resources:
      enabled: false
      value:
        limits:
          cpu: 0.1
          memory: 128Mi
        requests:
          cpu: 0.025
          memory: 128Mi

  mapproxinator:
    image:
      repository: mapproxinator
      tag: "v1.2.5"
      pullPolicy: Always
    env:
      logLevel: info
      poll:
        timeout:
          # FLAG
          frequencyMS: 5000
    resources:
      enabled: false
      value:
        limits:
          cpu: 0.1
          memory: 128Mi
        requests:
          cpu: 0.025
          memory: 128Mi

  mapproxy:
    image:
      repository: raster/docker-mapproxy
      tag: "v1.9.2"
      pullPolicy: Always
    socket: # for redis socket
      # FLAG
      connectionTimeoutSeconds: 0.1 # Set a connection timeout, nonnegative floating point number expressing *seconds*.
      # FLAG
      timeoutSeconds: 0.1 # Set a operation timeout nonnegative, floating point number expressing *seconds*.
    redis:
      tls: false
    wms:
      enabled: true
      replicaCount: 1
      resources:
        enabled: false
        value:
          # FLAG
          limits:
            cpu: 5
            memory: 3.2Gi
          requests:
            cpu: 1.25
            memory: 3.2Gi
    wmts:
      enabled: true
      replicaCount: 1
      resources:
        enabled: false
        value:
          # FLAG
          limits:
            cpu: 5
            memory: 3.2Gi
          requests:
            cpu: 1.25
            memory: 3.2Gi
    uwsgi:
      socket: 3031
      httpSocket: 8080
      # FLAG
      processes: 6
      # FLAG
      threads: 2
      disableLogging: true
      # FLAG
      timeoutSeconds: 8
      statsServer:
        stats: 1717
        statsMinify: true
    env:
      cors:
        enabled: true
        allowedOrigin: "*"
        allowedHeaders: "x-api-key"
      # FLAG
      requestsLogLevel: WARNING
      # FLAG
      logLevel: WARNING

  nginx:
    image:
      repository: nginx-otel-unprivileged
      tag: "v1.0.0"
      pullPolicy: Always
    enabled: true
    replicaCount: 1

    volume:
      storage: 1000Mi
      accessModes: ReadWriteOnce
    cache:
      enabled: false
      cachePath: /cache
      levels: "1:2" # levels sets up a two‑level directory hierarchy under
      keysZone: mapproxy_cache
      keysZoneSize: 10m # 10m is about 80,000 keys
      maxSize: 900m # physical memory
      inactive: 60m
      expirationTime: 60m
      useTempPath: "off"

    nginxTargetPort: 8080
    targetPort: 8080

    authorization:
      enabled: true
      token:
        queryName: token
      wms:
        enabled: true
        domain: "rasterWms"
      wmts:
        domain: "raster"

    route:
      enabled: true
      tls:
        enabled: true
        useCerts: true
      timeout:
        enabled: false # defaults to 30s by openshift
        duration: 60s # supported units (us, ms, s, m, h, d)

    ingress:
      enabled: false
      type: "nginx-org" # supported values: 'nginx-org' | 'nginx-kubernetes'
      path: /api/raster/v1
      tls:
        enabled: true
        useExternal: ""

    resources:
      enabled: false
      value:
        # FLAG
        limits:
          cpu: 0.25
          memory: 350Mi
        requests:
          cpu: 0.0625
          memory: 350Mi

  uwsgiExporter:
    image:
      repository: "timonwong/uwsgi-exporter"
      tag: "latest"
      pullPolicy: Always
    env:
      logLevel: info # one of [debug, info, warn, error]
    port: 9117
    resources:
      enabled: false
      value:
        limits:
          cpu: 0.1
          memory: 128Mi
        requests:
          cpu: 0.025
          memory: 128Mi

# ====================================================================================================
# Redis
# ====================================================================================================
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
  commonConfiguration: |-
    # Enable AOF https:redis.io/topics/persistence#append-only-file
    appendonly no
    protected-mode no
    # Disable RDB https, AOF persistence already enabled.
    save ""
  debug: false
  image:
    registry: docker.io
    repository: bitnamilegacy/redis
    tag: 7.2.1
  master:
    configuration: |
      maxmemory 5gb
      maxmemory-policy allkeys-lfu
    containerSecurityContext:
      enabled: false
    count: 1
    disableCommands:
      - FLUSHALL
    kind: StatefulSet
    persistence:
      accessModes:
        - ReadWriteMany
      enabled: false
      size: 1Gi
      storageClass: nfs
    podLabels:
      app: redis
      role: master
    podSecurityContext:
      enabled: false
    resources:
      # FLAG
      limits:
        cpu: 0.5
        memory: 5.5Gi
      requests:
        cpu: 0.125
        memory: 5.5Gi
    pullPolicy: Always
    serviceAccount:
      create: false
  metrics:
    enabled: false
    image:
      registry: docker.io
      repository: bitnamilegacy/redis-exporter
      tag: 1.55.0-debian-11-r2
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    containerSecurityContext:
      enabled: false

# ====================================================================================================
# PP-Geoserver
# ====================================================================================================
pp-geoserver:
  enabled: true
  imagePullPolicy: Always
  image:
    geoserverRepository: geoserver-os
    geoserverTag: "v2.0.0-2.26.0"
    sidecarRepository: raster/geoserver-polygon-parts
    sidecarTag: "v3.0.0"

  mclabels:
    component: backend
    partOf: serving
    owner: raster
    gisDomain: raster
    prometheus:
      enabled: true
      port: 9117
    longScraping: true

  # FLAG
  updateInterval: 10000

  replicaCount: 1

  nameOverride: "pp-geoserver" # release + fullname override
  fullnameOverride: "" # total override for deployment.

  tracing:
    enabled: true
  metrics:
    enabled: true
    prometheus:
      scrape: true
      port: 12345

  # FLAG
  initialMemory: "128M"
  # FLAG
  maxMemory: "756M"

  storage:
    fs:
      internalPvc:
        mountPath: "/data_dir"

  readiness:
    path: "/geoserver" # change it according to workspace name changing

  rootCerts:
    enabled: false

  pgSslAuth:
    enabled: false

  extraGeoserverEnv: |
    - name: COMMUNITY_EXTENSIONS
      value: "cog-plugin"
    - name: JAVA_OPTS
      value: >-
        "-DALLOW_ENV_PARAMETRIZATION=true
        -javaagent:/otel/opentelemetry-javaagent.jar
        -Dotel.traces.exporter=otlp
        -Dotel.exporter.otlp.protocol=http/protobuf
        -Dotel.exporter.otlp.compression=gzip"

  labels: {}
  annotations: {}
  podAnnotations: {}

  resources:
    enabled: false
    # FLAG
    limits:
      cpu: 2
      memory: 4500Mi
    requests:
      cpu: 2
      memory: 4000Mi

  sidecarResources:
    # FLAG
    limits:
      cpu: 200m
      memory: 250Mi
    requests:
      cpu: 200m
      memory: 250Mi

  service:
    type: ClusterIP
    port: 80
    labels: |
    annotations: |

  sideCar:
    env:
      logLevel: "info"
      logPretty: "false"
      # FLAG
      pollingInterval: 3000

      featureTypesBlackLists:
        tableNamesRegex:
          - '.*_history$'
          - '.*_valid$'
        tableNameStrings:
          - migrations
          - history
          - polygon_parts
          - base_parts
          - validation_parts

  nginx:
    imagePullPolicy: Always
    enabled: true
    replicaCount: 1
    clientMaxBodySize: 50m
    image:
      repository: nginx-otel-unprivileged
      tag: "v1.0.0"

    authorization:
      enabled: true
      domain: "raster"

    resources:
      enabled: false
      value:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

    route:
      enabled: true
      timeout:
        enabled: false # defaults to 30s by openshift
        duration: 60s # supported units (us, ms, s, m, h, d)
      tls:
        enabled: true
        useCerts: true

    ingress:
      enabled: false
      path: /api/raster/v1
      tls:
        enabled: true
        useExternal: ""
