apiVersion: v2
name: loki
description: A wrapper Loki Helm chart
type: application
version: 1.2.0
appVersion: 3.6.7
annotations:
  domain: infra
dependencies:
  - name: loki
    repository: https://grafana-community.github.io/helm-charts
    version: 7.0.0
