apiVersion: v2
name: loki
description: A wrapper Loki Helm chart
type: application
version: 1.0.1
appVersion: 3.4.2
annotations:
  domain: infra
dependencies:
  - name: loki
    repository: https://grafana-community.github.io/helm-charts
    version: 6.56.1
