grafana:
  extraLabels:
    mapcolonies.io/component: "infrastructure"
    mapcolonies.io/part-of: "monitoring"
    mapcolonies.io/owner: "infra"
  podLabels:
    mapcolonies.io/alloy-api-logs: "true"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"

  image:
    tag: 1.1.1

  rbac:
    create: false
  serviceAccount:
    create: false
    name: monitoring

  sidecar:
    image:
      repository: infra/kiwigrid/k8s-sidecar
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 32Mi
    dashboards:
      enabled: true
      label: "mapcolonies.io/grafana-dashboards"
      searchNamespace: null
      folderAnnotation: "mapcolonies.io/grafana-dashboards-folder"
      provider:
        foldersFromFilesStructure: true
    alerts:
      enabled: true
      label: "mapcolonies.io/grafana-alerts"
      searchNamespace: null

  # Alerting Teams Webhooks
  # This is a list of teams and their corresponding webhook URLs for Grafana alerting.
  # Example:
  # alertingTeamsWebhooks:
  #   - team: "infra"
  #     url: "https://hooks.slack.com/services/T00000000/B000
  alertingTeamsWebhooks: {}
    # - team: "infra"
    #   url: "bla"

  # Alerting Receiver Type
  # This is the type of receiver to use for Grafana alerting.
  # Example:
  # alertingReceiverType: "slack"
  alertingReceiverType: ""

  # Namespaces where teams deploy alert/dashboard ConfigMaps.
  # Grafana SA gets ConfigMap read access in each listed namespace.
  sidecarNamespaces: []

  envFromSecrets:
    - name: grafana-webhooks
      optional: true

  grafana.ini:
    unified_alerting:
      enabled: true
    metrics:
      enabled: "true"
    paths:
      plugins: /var/lib/grafana-plugins
