grafana:
  extraLabels:
    mapcolonies.io/component: "infrastructure"
    mapcolonies.io/part-of: "monitoring"
    mapcolonies.io/owner: "infra"
  podLabels:
    mapcolonies.io/alloy-api-logs: "true"
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"

  rbac:
    create: false
  serviceAccount:
    create: false
    name: monitoring

  grafana.ini:
    metrics:
      enabled: "true"
