{{- if and (not (lookup "v1" "ServiceAccount" .Release.Namespace "monitoring")) (.Values.serviceAccount.createIfNotExists) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
{{- end }}
