{{/*
Generate a Grafana Unified Alerting ConfigMap.

Usage in a team chart's templates/alerts.yaml:
  {{- if .Values.alerts.enabled }}
  {{ include "alerting-library.configmap" . }}
  {{- end }}

Required values:
  alerts.team                - team name matching a notification policy route (e.g. infra)
  alerts.rules[].name        - alert title (must be unique within this chart)
  alerts.rules[].expr        - PromQL expression; fires when result > 0
  alerts.rules[].severity    - one of: critical, warning, info
  alerts.rules[].summary     - short description for the notification

Optional values:
  alerts.folder              - Grafana folder name (default: "MapColonies Alerts")
  alerts.rules[].for         - duration before firing (default: "5m")
  alerts.rules[].description - extended context; supports {{ $labels.X }} syntax
*/}}
{{- define "alerting-library.configmap" -}}
{{- $baseName := .Release.Name -}}
{{- if not (contains .Chart.Name $baseName) -}}
  {{- $baseName = printf "%s-%s" $baseName .Chart.Name -}}
{{- end -}}

apiVersion: v1
kind: ConfigMap
metadata:
  # Result for you: "infra-alloy-alerts"
  name: {{ printf "%s-alerts" $baseName }}
  namespace: {{ .Release.Namespace }}
  labels:
    mapcolonies.io/grafana-alerts: "true"
    {{- include "alerting-library.labels" . | nindent 4 }}
data:
  alerts.yaml: |
    apiVersion: 1
    {{- if .Values.alerts.deleteRules }}
    deleteRules:
    {{- range .Values.alerts.deleteRules }}
      - orgId: {{ .orgId | default 1 }}
        uid: {{ .uid | quote }}
    {{- end }}
    {{- end }}
    groups:
      - orgId: 1
        name: {{ $baseName }}
        folder: {{ .Values.alerts.folder | default "MapColonies Alerts" | quote }}
        interval: 1m
        rules:
        {{- range .Values.alerts.rules }}
          - uid: {{ printf "%s/%s/%s" $.Release.Namespace $baseName .name | sha256sum | trunc 8 | quote }}
            title: {{ .name | quote }}
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: prometheus
                model:
                  datasource:
                    type: prometheus
                    uid: prometheus
                  editorMode: code
                  expr: {{ .expr }}
                  instant: true
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: A
              - refId: C
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params: [0]
                        type: gt
                      operator:
                        type: and
                      query:
                        params: [A]
                      reducer:
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: classic_conditions
            noDataState: {{ .noDataState | default "OK" | quote }}
            execErrState: {{ .execErrState | default "Error" | quote }}
            for: {{ .for | default "5m" | quote }}
            labels:
              severity: {{ .severity }}
              alert_team: {{ $.Values.alerts.team }}
            annotations:
              summary: {{ .summary }}
              description: {{ .description | default "" | quote }}
        {{- end }}
{{- end -}}

{{/*
Common labels shared by all resources generated by this library.
*/}}
{{- define "alerting-library.labels" -}}
app.kubernetes.io/managed-by: {{ .Release.Service }}
helm.sh/chart: alerting-library
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
