apiVersion: v2
name: raster-export
description: A Helm chart for Raster export services
annotations:
  domain: raster
type: application
version: 1.1.0
dependencies:
  - name: gpkg-merger
    version: 2.2.3
    condition: exporter-gpkg-merger.enabled
    alias: exporter-gpkg-merger
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster

  - name: exporter-trigger
    version: 3.3.0
    condition: exporter-trigger.enabled
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster

  - name: overseer
    version: 2.11.1
    condition: exporter-overseer.enabled
    alias: exporter-overseer
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster

  - name: polygon-parts-worker
    version: 2.3.1
    condition: exporter-polygon-parts-worker.enabled
    alias: exporter-polygon-parts-worker
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster
