# ====================================================================================================
# Exporter-Gpkg-Merger
# ====================================================================================================
exporter-gpkg-merger:
  enabled: true
  image:
    repository: raster/tiles-merger-service
    tag: "v2.2.2"
  replicaCount: 1
  isExporter: true

  env:
    general:
      validate: false
      # batchMaxBytes: 838860800 # 800MB
    metrics:
      enabled: false
      # measurementBuckets: "[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 15, 50,250, 500]"
    TASK:
      types:
        - jobType: "Export"
          taskType: "tilesExporting"
      pollingTime: 2000
    heartbeat:
      intervalMs: 3000
    logging:
      logLevel:
        aspNetCore: "Information"

  resources:
    enabled: false
    value:
      limits:
        cpu: 1
        memory: 4Gi
      requests:
        cpu: 0.25
        memory: 4Gi

# ====================================================================================================
# Exporter-Trigger
# ====================================================================================================
exporter-trigger:
  enabled: true
  image:
    repository: raster/exporter-trigger
    tag: v3.2.1
  replicaCount: 1
  imagePullPolicy: IfNotPresent

  tracing:
    enabled: true

  env: {}
    # estimatedStorageCalculation:
    #   jpegTileEstimatedSizeInBytes: 27000
    #   pngTileEstimatedSizeInBytes: 263000
    #   storageFactorBuffer: 1.25

  resources:
    enabled: false
    value:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.25
        memory: 1Gi

# ====================================================================================================
# Exporter-Overseer
# ====================================================================================================
exporter-overseer:
  enabled: true
  image:
    repository: raster/overseer
    tag: v2.5.2
    pullPolicy: IfNotPresent
  replicaCount: 1

  mclabels:
    prometheus:
      enabled: true
      port: 9500

  metrics:
    enabled: true
    prometheus:
      scrape: true
      port: 9500

  instanceType: "export"

  jobDefinitions:
    jobs:
      export:
        downloadPath: "downloads"

  resources:
    enabled: false
    value:
      limits:
        cpu: 2.5
        memory: 1Gi
      requests:
        cpu: 0.75
        memory: 1Gi

  livenessProbe:
    timeoutSeconds: 30

  readinessProbe:
    timeoutSeconds: 30

# ====================================================================================================
# Files-Server
# ====================================================================================================
files-server:
  enabled: true
  nginx:
    enabled: true
    replicaCount: 1
    image:
      repository: nginx-otel-unprivileged
      tag: "v1.0.0"
    imagePullPolicy: IfNotPresent

    resources:
      enabled: false
      value:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

    route:
      enabled: true
      routesMapping:
        - path: /api/raster/v1
          host: ""
      rewriteTarget: "/"
      tls:
        enabled: true
        useCerts: true
#ask nati
    # ingress:
    #   enabled: false
    #   type: "nginx-org" # supported values: 'nginx-org' | 'nginx-kubernetes'
    #   path: /
    #   host: ""
    #   tls:
    #     enabled: false
    #     useExternal: ""
    #   cors:
    #     enabled: true
    #     origin: "*"

# ====================================================================================================
# Nginx-S3-Gateway
# ====================================================================================================
nginx-s3-gateway:
  enabled: true
  image:
    repository: common/nginx-s3-gateway
    tag: v3.0.2
  replicaCount: 1

  authorization:
    domain: ""
    url: ""

  env:
    tracing:
      enabled: false
    metrics:
      enabled: false

  s3:
  #   bucketName: ""
  #   accessKeyId: ""
  #   secretAccessKey: ""
    server: ""
    debug: false

  resources:
    enabled: false
    value:
      limits:
        cpu: 500m
        memory: 900Mi
      requests:
        cpu: 125m
        memory: 900Mi

  route:
    enabled: false
    path: /api/raster/v1
    timeout:
      enabled: false # defaults to 30s by openshift
      duration: 60s # supported units (us, ms, s, m, h, d)
    tls:
      enabled: true
      useCerts: true

  ingress:
    enabled: false
    type: "nginx-kubernetes" # supported values: 'nginx-org' | 'nginx-kubernetes'
    host: ""
    path: ""

# ====================================================================================================
# Exporter-Cleanup
# ====================================================================================================
exporter-cleanup:
  enabled: false
  image:
    repository: "exporter-cleanup"
    tag: "v3.0.0"
    pullPolicy: IfNotPresent
  cron:
    schedule: "* * * * *"
    # successfulJobsHistoryLimit: 1
    # failedJobsHistoryLimit: 3
    # concurrencyPolicy: Forbid
    # restartPolicy: OnFailure
  env:
    logLevel: info
    s3:
      maxRetries: 3
      prefix: ""
      batchSize: 100
  resources:
    enabled: false
    value:
      limits:
        cpu: 0.25
        memory: 256Mi
      requests:
        cpu: 0.0625
        memory: 256Mi
