apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-alloy
  namespace: {{ .Release.Namespace }}
  labels:
    mapcolonies.io/owner: infra
data:
  config.alloy: |-
{{ tpl (.Files.Get "files/config.alloy.gotmpl") . | indent 4 }}
