apiVersion: v2
description: Infra Monitoring stack
name: infra-monitoring
annotations:
  domain: infra
version: 2.0.0
keywords:
  - prometheus
  - blackbox
  - monitoring
  - alertmanager
type: application

dependencies:
  - name: prometheus-blackbox-exporter
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    version: "9.1.0"
    condition: blackbox-exporter.enabled
    alias: blackbox-exporter
  - name: alertmanager
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    version: "1.13.1"
    condition: alertmanager.enabled
  - name: prometheus
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    version: "26.0.1"
    condition: prometheus.enabled
  - name: grafana
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    version: "8.8.2"
    condition: grafana.enabled
  - name: opentelemetry-collector
    version: "0.111.0"
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    condition: opentelemetry-collector.enabled
  - name: opentelemetry-collector
    version: "0.111.0"
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    condition: opentelemetry-collector-internal.enabled
    alias: opentelemetry-collector-internal
  - name: tempo-distributed
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    version: "1.28.0"
    condition: tempo-distributed.enabled
  - name: kube-state-metrics
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    version: "5.28.0"
    condition: kube-state-metrics.enabled
  - name: elasticsearch-alertmanager-connector
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    version: "1.0.0"
    condition: elasticsearch-alertmanager-connector.enabled
  - name: prometheus-postgres-exporter
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    version: "6.8.1"
    condition: postgres-exporter.enabled
    alias: postgres-exporter
  - name: prometheus-redis-exporter
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    version: "6.8.0"
    condition: redis-exporter.enabled
    alias: redis-exporter
  - name: loki
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    version: "6.28.0"
    condition: loki.enabled
  - name: alloy
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    version: "1.1.1"
    condition: alloy.enabled
# BLA
