apiVersion: v2
name: raster-ingestion
description: A Helm chart for Raster ingestion services
annotations:
  domain: raster
type: application
version: 1.1.0
dependencies:
  - name: gpkg-merger
    version: 2.2.3
    condition: gpkg-merger.enabled
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster

  - name: mapproxy-api
    version: 1.14.0
    condition: mapproxy-api.enabled
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster

  - name: cache-seeder
    version: 2.3.2
    condition: cache-seeder.enabled
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster

  - name: ingestion-trigger
    version: 4.5.1
    condition: ingestion-trigger.enabled
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster

  - name: overseer
    version: 2.11.1
    condition: overseer.enabled
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster

  - name: geoserver-api
    version: 2.1.0
    condition: geoserver-api.enabled
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster

  - name: polygon-parts-worker
    version: 2.3.1
    condition: polygon-parts-worker.enabled
    alias: polygon-parts-worker
    repository: oci://acrarolibotnonprod.azurecr.io/helm/raster
