# ====================================================================================================
# Gpkg-Merger
# ====================================================================================================
gpkg-merger:
  enabled: true
  image:
    repository: raster/tiles-merger-service
    tag: "v2.2.2"
  replicaCount: 1
  isExporter: false

  env:
    protocol: TCP
    general:
      validate: false
      # batchMaxBytes: 838860800 # 800MB
    metrics:
      enabled: false
      # measurementBuckets: "[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 15, 50,250, 500]"
    TASK:
      types:
        - jobType: "Ingestion_Update"
          taskType: "tilesMerging"
        - jobType: "Ingestion_New"
          taskType: "tilesMerging"
        - jobType: "Ingestion_Swap_Update"
          taskType: "tilesMerging"
      pollingTime: 2000
    heartbeat:
      intervalMs: 3000
    logging:
      logLevel:
        aspNetCore: "Information"

  resources:
    enabled: false
    value:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 0.5
        memory: 4Gi
# no need for a route 
  # route:
  #   enabled: false
  #   path: /
  #   timeout:
  #     enabled: false # defaults to 30s by openshift
  #     duration: 60s # supported units (us, ms, s, m, h, d)

# ====================================================================================================
# MapProxy-Api
# ====================================================================================================
mapproxy-api:
  enabled: true
  image:
    repository: raster/mapproxy-api
    tag: "v1.11.3"
    pullPolicy: IfNotPresent
  replicaCount: 1

  db:
    schema: "MapproxyConfig"

  env:
    logLevel: info
    # mapproxyCache:
    #   grids: WorldCRS84
    #   upscaleTiles: 18
    #   directoryLayout: tms

  redis:
    enabled: true
    host: "raster-mapproxy-redis-master"
    auth:
      enableRedisUser: true
      username: ""
      password: "password"

  resources:
    enabled: false
    value:
      limits:
        cpu: 0.25
        memory: 250Mi
      requests:
        cpu: 0.0625
        memory: 250Mi

# ====================================================================================================
# Discrete-Cleanup
# ====================================================================================================
discrete-cleanup:
  enabled: false

# ====================================================================================================
# Cache-Seeder
# ====================================================================================================
cache-seeder:
  enabled: true
  image:
    repository: "cache-seeder"
    tag: "v2.1.2"
    pullPolicy: IfNotPresent

  replicaCount: 5
  env:
    logLevel: info
    seedConcurrency: 25
    # invalidBboxInitialBufferMeters: 200
    # invalidBboxRetryLimit: 5

  resources:
    enabled: false
    value:
      limits:
        cpu: 500m
        memory: 1000Mi
      requests:
        cpu: 500m
        memory: 1000Mi

# ====================================================================================================
# Ingestion-Trigger
# ====================================================================================================
ingestion-trigger:
  enabled: true
  imagePullPolicy: IfNotPresent
  image:
    repository: raster/ingestion-trigger
    tag: v4.1.1
  replicaCount: 1

  metrics:
    enabled: true

  env:
    forbiddenTypesForParallelIngesion:
      - Ingestion_New
      - Ingestion_Update
      - Ingestion_Swap_Update
    productReader:
      maxVerticesPerChunk: 20000
    supportedIngestionSwapTypes:
      - productType: "RasterVectorBest"
        productSubType: "עבירות"

  resources:
    enabled: false
    value:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.25
        memory: 1Gi

# ====================================================================================================
# Overseer
# ====================================================================================================
overseer:
  enabled: true
  image:
    repository: raster/overseer
    tag: v2.5.2
    pullPolicy: IfNotPresent
  replicaCount: 1

  mclabels:
    prometheus:
      enabled: true
      port: 9500

  metrics:
    enabled: true
    prometheus:
      scrape: true
      port: 9500

  instanceType: "ingestion"

  jobDefinitions:
    tasks:
      merge:
        useNewTargetFlagInUpdate: true
      seed: {}
        # maxZoom: 21
        # skipUncached: true
        # zoomThreshold: 16
        # maxTilesPerSeedTask: 500000

  resources:
    enabled: false
    value:
      limits:
        cpu: 2.5
        memory: 1Gi
      requests:
        cpu: 0.75
        memory: 1Gi

  livenessProbe:
    timeoutSeconds: 30

  readinessProbe:
    timeoutSeconds: 30

# ====================================================================================================
# Geoserver-Api
# ====================================================================================================
geoserver-api:
  enabled: true
  imagePullPolicy: IfNotPresent
  image:
    repository: raster/geoserver-api
    tag: v2.0.0
  replicaCount: 1

  metrics:
    enabled: true

  env: {}
    # disableHttpClientLogs: false
    # srs: "EPSG:4326"
    # numOfDecimals: 100
    # maxFeatures: 1000
  db:
    schema: "polygon_parts"
    # dbType: "postgis"

  resources:
    enabled: false
    value:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.25
        memory: 1Gi
