# ====================================================================================================
# Gpkg-Merger
# ====================================================================================================
gpkg-merger:
  image:
    repository: raster/tiles-merger-service
    tag: "v2.2.3"
  isExporter: false
  env:
    general:
      validate: false
    TASK:
      types:
        - jobType: "Ingestion_New"
          taskType: "tilesMerging"
        - jobType: "Ingestion_Update"
          taskType: "tilesMerging"
        - jobType: "Ingestion_Swap_Update"
          taskType: "tilesMerging"
      pollingTime: 3000 # TODO: fix default value inside the service
    heartbeat:
      intervalMs: 3000 # TODO: fix default value inside the service


# ====================================================================================================
# MapProxy-Api
# ====================================================================================================
mapproxy-api:
  image:
    repository: raster/mapproxy-api
    tag: "v1.13.0"
  configManagement:
    offlineMode: true
  db:
    schema: "MapproxyConfig"


# ====================================================================================================
# Cache-Seeder
# ====================================================================================================
cache-seeder:
  image:
    repository: "raster/cache-seeder"
    tag: "v2.3.2"
  env:
    seedConcurrency: 25


# ====================================================================================================
# Ingestion-Trigger
# ====================================================================================================
ingestion-trigger:
  image:
    repository: raster/ingestion-trigger
    tag: v4.4.0
  configManagement:
    offlineMode: true
  env:
    productReader:
      maxVerticesPerChunk: 20000
    supportedIngestionSwapTypes:
      - productType: "RasterVectorBest"
        productSubType: "עבירות"


# ====================================================================================================
# Overseer
# ====================================================================================================
overseer:
  image:
    repository: raster/overseer
    tag: v2.9.0
  configManagement:
    offlineMode: true
  instanceType: "ingestion"


# ====================================================================================================
# Geoserver-Api
# ====================================================================================================
geoserver-api:
  image:
    repository: raster/geoserver-api
    tag: v2.1.0
  configManagement:
    offlineMode: true
  db:
    schema: "polygon_parts"
    dbType: "postgis"

# ====================================================================================================
# Polygon-Parts-Worker
# ====================================================================================================
polygon-parts-worker:
  image:
    repository: raster/polygon-parts-worker
    tag: v2.3.0
  instanceType: ingestion
  configManagement:
    offlineMode: true
  jobManagement:
    config:
      dequeueIntervalMs: 30000
  jobDefinitions:
    tasks:
      validation:
        reportsDownloadPath: "/validation-reports" 
