{{- if dig "datasources" "postgres" (list) (toJson .Values | fromJson) -}}
{{- $base := include "datasource-library.basename" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $base }}-grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    mapcolonies.io/grafana-datasources: "true"
type: Opaque
stringData:
  {{ $base }}.yaml: |
{{ include "datasource-library.postgres" . | indent 4 }}
{{- end }}
